[package]
name = "main"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
description = ""
repository = ""
publish = false

[workspace]
members = [
    "crates/*",
]

[dependencies.windows]
version = "0.44.0"
features = [
    "implement",
    "Win32_Foundation",
]
